---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: consul-counting-dashboard
  namespace: default
spec:
  prefix: /
  host: dev.emojify.today
  service: emojify-website-sidecar-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin

---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: consul-api-mapping
  namespace: default
spec:
  prefix: /api/
  timeout_ms: 20000
  host: dev.emojify.today
  service: emojify-api-sidecar-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
