# Define public loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: counting-dashboard
spec:
  selector:
    app: dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9002
  type: LoadBalancer
